In [36]:
#new way to calculate "accuracy"
#read in ref and imp files as before
#for each of 5000 SNPs
#for each person
#compare the reference with imputed genotype 
import pandas as pd
import numpy as np

orig10_file = pd.read_csv('ref_10.txt', delimiter=' ', header = None)
inf10_file = pd.read_csv('inf_01.txt', delimiter=' ', header = None)

accuracy_mtx = np.zeros((orig10_file.shape[0], int((orig10_file.shape[1] - 5) / 2)))
num_SNPs = orig10_file.shape[0]
                        
for loc in range(num_SNPs):
    refSNPs = orig10_file.loc[loc, 5:] #change file name here
    infSNPs = inf10_file.loc[loc, 5:]
    for hap in range(int(refSNPs.size / 2)):
        ref_sum = refSNPs[2*hap + 5] + refSNPs[2*hap + 6]
        if ref_sum == 0:
            accuracy_mtx[loc, hap] = np.abs(1 - infSNPs[3*hap + 5])
        elif ref_sum == 1:
            accuracy_mtx[loc, hap] = np.abs(1 - infSNPs[3*hap + 6])
        elif ref_sum == 2:
            accuracy_mtx[loc, hap] = np.abs(1 - infSNPs[3*hap + 7])



In [37]:
print(accuracy_mtx[:10,:10])

[[0.    0.005 0.    0.006 0.01  0.008 0.    0.008 0.008 0.005]
 [0.017 0.044 0.017 0.044 0.068 0.062 0.022 0.064 0.068 0.044]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.012 0.113 0.988 0.12  0.779 0.193 0.012 0.194 0.215 0.111]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.268 0.243 0.366 0.219 0.819 0.191 0.262 0.186 0.187 0.252]
 [0.004 0.033 0.004 0.034 0.068 0.054 0.004 0.056 0.055 0.036]
 [0.001 0.011 0.001 0.011 0.02  0.026 0.001 0.02  0.019 0.011]
 [0.03  0.021 0.032 0.02  0.011 0.013 0.027 0.011 0.011 0.023]
 [0.008 0.086 0.992 0.089 0.831 0.145 0.008 0.148 0.161 0.083]]
